name: Build Report Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Step
        run: echo "Build Successful"

  build-report:
    runs-on: ubuntu-latest
    steps:
      - name: Build Report
        run: echo "Build Status SUCCESS"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploy Successful"

  deploy-report:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Report
        run: echo "Deploy Status SUCCESS"
